import _ from 'underscore';
import PositionableObject from 'common/models/positionable-object';
import Vector2 from 'common/math/vector2';
import Nucleon from 'models/nucleon';

/**
 * This class models the behavior of a neutron source, i.e. some sort of
 *   device that can generate neutrons.
 */
var NeutronSource = PositionableObject.extend({

    defaults: _.extend({}, PositionableObject.prototype.defaults, {
        // Angle, in radians, at which the neutron should be fired
        firingAngle: 0,
        // Velocity of neutrons generated by this source
        neutronVelocity: 1.75
    }),

    initialize: function(attributes, options) {
        PositionableObject.prototype.initialize.apply(this, [attributes, options]);

        // Cached objects
        this._velocity = new Vector2();
    },

    /**
     * Commands the neutron source to generate a new neutron.
     */
    generateNeutron: function() {
        var newNeutron = Nucleon.create({
            type: Nucleon.NEUTRON,
            position: this.get('position'),
            velocity: this._velocity.set(
                this.get('neutronVelocity') * Math.cos(this.get('firingAngle')),
                this.get('neutronVelocity') * Math.sin(this.get('firingAngle'))
            ),
            tunnelingEnabled: false
        });

        this.trigger('neutron-generated', newNeutron);
    }

});

export default NeutronSource;